### ISSUE TITLE
【メモ】Break week中の修正点リスト

### ISSUE THREAD

**Issue by smzgk** [smzgk/Fab-Academy-2016#1]
#### 1) Documentation Revision
- [ ] revise the document of wk05: 3D SCANNING AND PRINTING（#6）
  - add basic information
  - correct the document
- [ ] revise the document of wk06: ELECTRONICS DESIGN (WEEK 1 OF 2)（#7）
  - add basic information(Voltage...)
  - add description on how to use EAGLE
  - correct the document
- [ ] revise the document of wk07: COMPUTER-CONTROLLED MACHINING（#8）
  - add basic information
  - add description on how to use shopbot
  - correct the document
#### 2) Site Layout Revision
- [x] サイト画像に圧縮処理を加える（#2）
  - 全体で40MB/人に抑える必要あり
  - [JPEG/PNG Minimizer](http://optimizilla.com)
- [ ] 3Dデータの表示方法を変更する（#3）
  - Fusion 360のembedだと重いので、他の方法を検討する
- [ ] ホーム画面のレイアウトを縦スクロールに変更する（#4）
- [ ] Weekly Assignment一覧のレイアウトをスタイリッシュなものにする（#5）
#### 3) Assignment wk08
- [ ] add documents of wk08（#9）
#### 4) Add contents
- [ ] wk07: make laundry basket and add 'hero photo'（#10）
