### ISSUE TITLE
add datasheet contents of wk08

### ISSUE THREAD

**Issue by smzgk** [smzgk/Fab-Academy-2016#24]
refer #9 
#### TODO
- [ ] add overview of datasheet
- [ ] add description of major abbreviations of datasheet
#### nice to have
- [ ] Run programme by command line on windows
